apiVersion: v1

kind: Service

metadata:

  name: server-demo

  labels:

    app: server-demo

spec:

  type: ClusterIP

  ports:

    - port: 8080

      name: http-demo

  selector:

    app: server-demo
---
apiVersion: apps/v1

kind: Deployment
metadata:

  name: server-demo

  labels:

    app: server-demo

spec:

  replicas: 5

  selector:

    matchLabels:

      app: server-demo

  template:

    metadata:

      labels:

        app: server-demo

        version: "v7"
    spec:

      containers:

        - image: target/myimage

          name: server-demo

          ports:

            - containerPort: 8080

          env:

            - name: NAME

              value: demo

